# Generated by Django 4.0.3 on 2025-04-29 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanComptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateTimeField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('total_actif', models.FloatField()),
                ('total_passif', models.FloatField()),
                ('capitaux_propres', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantite', models.FloatField()),
                ('prix_unitaire', models.FloatField()),
                ('montant_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionBancaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('date_valeur', models.DateTimeField()),
                ('credit', models.FloatField()),
                ('debit', models.FloatField()),
                ('libelle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=50)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('solde_ouverture', models.FloatField()),
                ('solde_cloture', models.FloatField()),
                ('titulaire_compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_bancaires', to='inov.contactinformation')),
                ('transactions', models.ManyToManyField(to='inov.transactionbancaire')),
            ],
        ),
        migrations.CreateModel(
            name='Facturee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateTimeField()),
                ('numero_facture', models.CharField(max_length=100, unique=True)),
                ('tva', models.FloatField()),
                ('montant_ttc', models.FloatField()),
                ('methode_de_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('informations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_emises', to='inov.contactinformation')),
                ('informations_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_recues', to='inov.contactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type_document', models.CharField(choices=[('facture', 'Facture'), ('releve', 'Relevé'), ('bilan', 'Bilan')], max_length=20)),
                ('champs_choisis', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
