# Generated by Django 4.0.3 on 2025-05-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0002_bilancomptable_contactinformation_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturee',
            name='produits',
            field=models.ManyToManyField(related_name='factures', to='inov.produit'),
        ),
    ]
