# Generated by Django 4.0.3 on 2025-05-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0003_facturee_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
