# Generated by Django 4.0.3 on 2025-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0006_facturee_insights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturee',
            name='date_echeance',
            field=models.CharField(max_length=100),
        ),
    ]
