# Generated by Django 4.0.3 on 2025-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0003_facturee_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturee',
            name='insights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
