# Generated by Django 4.0.3 on 2025-05-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0004_facture_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='img',
        ),
    ]
