# Generated by Django 4.0.3 on 2025-05-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0005_alter_facturee_date_echeance'),
        ('inov', '0007_remove_facture_img'),
    ]

    operations = [
    ]
