# Generated by Django 4.0.3 on 2025-05-10 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0008_merge_20250510_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Fichier', 'verbose_name_plural': 'Fichiers'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dossier', 'verbose_name_plural': 'Dossiers'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='image',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='comptable',
        ),
        migrations.AddField(
            model_name='bilancomptable',
            name='insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='extraction_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='folder',
            name='color',
            field=models.CharField(default='#6c757d', max_length=20, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='relevebancaire',
            name='insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='extraction_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du dossier'),
        ),
    ]
