# Generated by Django 4.0.3 on 2025-05-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0009_alter_file_options_alter_folder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilancomptable',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='inov.file'),
        ),
        migrations.AddField(
            model_name='facturee',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='inov.file'),
        ),
        migrations.AddField(
            model_name='relevebancaire',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releve', to='inov.file'),
        ),
    ]
