# Generated by Django 4.0.3 on 2025-05-11 10:35

from django.db import migrations, models
import django.db.models.deletion
import inov.models


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0010_bilancomptable_file_facturee_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='HT',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='TOTAL',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='TVA',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='status',
        ),
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.CharField(blank=True, default='À définir', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='file',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='inov.file'),
        ),
        migrations.AddField(
            model_name='facture',
            name='informations',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures_emises', to='inov.contactinformation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='informations_client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures_recues', to='inov.contactinformation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='methode_de_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ttc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(default=inov.models.generate_default_facture_numero, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='produits',
            field=models.ManyToManyField(related_name='factures', to='inov.produit'),
        ),
        migrations.AddField(
            model_name='facture',
            name='tva',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Facturee',
        ),
    ]
