# Generated by Django 4.0.3 on 2025-05-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0011_remove_facture_ht_remove_facture_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilancomptable',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='inov.client'),
        ),
        migrations.AddField(
            model_name='bilancomptable',
            name='comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='inov.comptable'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='inov.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='inov.comptable'),
        ),
        migrations.AddField(
            model_name='relevebancaire',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='inov.client'),
        ),
        migrations.AddField(
            model_name='relevebancaire',
            name='comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='inov.comptable'),
        ),
    ]
