# Generated by Django 4.0.3 on 2025-05-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0012_bilancomptable_client_bilancomptable_comptable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilancomptable',
            name='status',
            field=models.CharField(default='Non Validé', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='status',
            field=models.CharField(default='Non Validé', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relevebancaire',
            name='status',
            field=models.CharField(default='Non Validé', max_length=200, null=True),
        ),
    ]
