# Generated by Django 4.0.3 on 2025-05-11 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inov', '0014_alter_file_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractionconfiguration',
            options={'ordering': ['-created_at'], 'verbose_name': "Configuration d'extraction", 'verbose_name_plural': "Configurations d'extraction"},
        ),
        migrations.AddField(
            model_name='extractionconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='extractionconfiguration',
            name='champs_choisis',
            field=models.JSONField(verbose_name='Champs sélectionnés'),
        ),
        migrations.AlterField(
            model_name='extractionconfiguration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du modèle'),
        ),
        migrations.AlterField(
            model_name='extractionconfiguration',
            name='type_document',
            field=models.CharField(choices=[('facture', 'Facture'), ('releve', 'Relevé'), ('bilan', 'Bilan')], max_length=20, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='extractionconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_extraction_models', models.JSONField(blank=True, help_text="Modèles d'extraction par défaut pour chaque type de document", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
