# Generated by Django 4.0.3 on 2025-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0016_folder_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='type',
            field=models.CharField(choices=[('bilan', 'Bilan'), ('facture', 'Facture'), ('releve', 'Relevé'), ('mixte', 'Mixte')], default='mixte', max_length=10, verbose_name='Type de dossier'),
        ),
    ]
