# Generated by Django 4.0.3 on 2025-05-12 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inov', '0017_folder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionconfiguration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='type',
            field=models.CharField(choices=[('bilan', 'Bilan'), ('facture', 'Facture'), ('releve', 'Relevé'), ('mixte', 'Mixte')], max_length=10, verbose_name='Type de dossier'),
        ),
    ]
