# Generated by Django 4.0.3 on 2025-05-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0018_alter_extractionconfiguration_user_alter_folder_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilancomptable',
            name='date_echeance',
        ),
    ]
