# Generated by Django 4.0.3 on 2025-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inov', '0019_remove_bilancomptable_date_echeance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilancomptable',
            name='date_debut',
            field=models.CharField(blank=True, default='À définir', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bilancomptable',
            name='date_fin',
            field=models.CharField(blank=True, default='À définir', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relevebancaire',
            name='date_debut',
            field=models.CharField(blank=True, default='À définir', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relevebancaire',
            name='date_fin',
            field=models.CharField(blank=True, default='À définir', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionbancaire',
            name='date',
            field=models.CharField(blank=True, default='À définir', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionbancaire',
            name='date_valeur',
            field=models.CharField(blank=True, default='À définir', max_length=100, null=True),
        ),
    ]
